export const projects = [
    {
        title: "Splash", 
        description: "Wine pairing MERN Full Stack Application",
        stack: "MERN stack, React.js, GraphQL, Espress.js, Node.js, MongoDB, Mongoose, JWT",
        image:"https://user-images.githubusercontent.com/122245852/263687745-5669a933-d0a1-4af8-8298-15555d3ccd52.png",
        link: "https://splash-0f0eb7a8bfa4.herokuapp.com/", 
        git:"https://github.com/jnaoroji/final_project_JN",
    },
    {
        title: "Bloom and Barter", 
        description: "Community Plant Swap Full Stack Application",
        stack: "HTML, Tailwind-CSS, JavaScript, Express.js, Node.js, MySQL, Dotenv, Sequelize, Handlebars",
        image:"https://user-images.githubusercontent.com/122245852/258636311-d2c4e21e-900f-4d92-a648-bc0b43e4c0ef.png",
        link: "https://bloom-and-barter-3911749eadd3.herokuapp.com", 
        git:"https://github.com/jnaoroji/Bloom_and_Barter",
    },
    {
        title: "Gif it a Try", 
        description: "Guess the Song Name Application",
        stack: "HTML, Tailwind-CSS, JavaScript, Giphy API, Music Brianz API",
        image:"https://user-images.githubusercontent.com/122245852/258641578-d3adfbba-609a-4aa6-b28b-8174a337ee3a.png",
        link: "https://jnaoroji.github.io/gif_it_a_try_interactive_front_end_application/", 
        git:"https://github.com/jnaoroji/gif_it_a_try_interactive_front_end_application",
    },
    {
        title: "Tech Blog", 
        description: "CMS style Tech blog using the MVC Paradigm",
        stack: "MySQL, MVC paradigm, express-session, express-handlebars, connect-session-sequelize, Dotenv, bcrypt",
        image:"https://user-images.githubusercontent.com/122245852/258644365-c822a1f2-5225-4cb7-8cbc-75d399e61c38.png",
        link: "https://jenny-tech-blog-5f80e3182e28.herokuapp.com/", 
        git:"https://github.com/jnaoroji/MVC_Tech_Blog_JN",
    },
    {
        title: "Weather Dashboard", 
        description: "Weather Dashboard Application using Server-Side APIs",
        stack: "HTML, CSS, JavaScript, Local Storage, Open Weather Map API",
        image:"https://user-images.githubusercontent.com/122245852/258641805-899e21f3-3d31-4ff3-beaf-82dd34efd82b.png",
        link: "https://jnaoroji.github.io/weather-dashboard-SSAPIs/", 
        git:"https://github.com/jnaoroji/weather-dashboard-SSAPIs",
    },
    {
        title: "Work Day Scheduler", 
        description: "Work Day Schedule Application using Third-Party Apis",
        stack: "HTML, CSS, JavaScript, Local Storage, days.js library, jQuery",
        image:"https://user-images.githubusercontent.com/122245852/258641976-9bcb6839-7d43-486b-935b-dda569eb6c55.png",
        link: "https://jnaoroji.github.io/Schedule-WorkDay-JN/", 
        git:"https://github.com/jnaoroji/Schedule-WorkDay-JN",
    },
    {
        title: "Note Taker", 
        description: "Express.js Notetaker Application",
        stack: "HTML, CSS, JavaScript, Express.js, express-router, Node.js",
        image:"https://user-images.githubusercontent.com/122245852/258644192-122b50dc-4631-4a7c-a272-298c08c2f255.png",
        link: "https://express-note-taker-jn.herokuapp.com/", 
        git:"https://github.com/jnaoroji/Express.js_Note_Taker_JN",
    },
    {
        title: "Yoga Gym", 
        description: "Marketing Website for a Yoga Business",
        stack: "UI/UX",
        image:"https://user-images.githubusercontent.com/122245852/265583933-61659d5e-270e-4450-a7a3-cbd1a1038ea4.png",
        link: "https://yogagym.co.nz/home", 
        git:"https://yogagym.co.nz/home",
    }

]